version: "3.1"

services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - db
    networks:
      - skynet
  db:
    image: mongo:3.4
    volumes:
      - dbdata:/mongo/db
    networks:
      - skynet

networks:
  skynet:
    driver: bridge

volumes:
  dbdata:
